"""Where a run keeps what, under its directory: an open profile writes there, and the monitor and the report read."""

RUN = "run.json"
"""Which run the directory is: its id in the registry (`rollout_train.registry`)."""
LEDGER = "ledger"
"""The run's tables, the checkpoints and the fences, in files (unless the profile names another place)."""
FEED = "feed"
"""The monitor's feed."""
BLOBS = "blobs"
"""Episodes' trajectories and checkpoints' files (unless the profile names a blob store)."""
PROCESSES = "engine.json"
"""The engines' processes, noted so that a later process can end them if this one dies without doing so."""
